services:
  api:
    build:
      context: ../..
      dockerfile: ops/docker/api.Dockerfile
    ports:
      - "5000:8080"
  ui:
    build:
      context: ../..
      dockerfile: ops/docker/ui.Dockerfile
    ports:
      - "5001:8080"
  mock-lwrp-device:
    build:
      context: ../../src/infrastructure/Lwrp.MockDevice
    ports:
      - "10093:93"
